apiVersion: apps/v1
kind: Deployment
metadata:
  name: redes-app
  labels:
    app: redes-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redes-app
  template:
    metadata:
      labels:
        app: redes-app
    spec:
      containers:
      - name: redes-app
        image: tuacr2026.azurecr.io/redes-app:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"